apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 2
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: kinhnv1801/kubeexample:service1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer