apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  selector:
    matchLabels:
      app: service3
  replicas: 2
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: kinhnv1801/kubeexample:service3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-service3
spec:
  selector:
    app: service3
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  