apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-apigateway
spec:
  replicas: 10
  selector:
    app: apigateway
  template:
    metadata:
      name: apigateway
      labels:
        app: apigateway
    spec:
      containers:
        - name: pod-apigateway
          image: kinhnv1801/kubeexample:apigateway
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 80

