apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-service1
spec:
  replicas: 10
  selector:
    app: service1
  template:
    metadata:
      name: service1
      labels:
        app: service1
    spec:
      containers:
        - name: pod-service1
          image: kinhnv1801/kubeexample:service1
          ports:
            - containerPort: 80
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD 
---
apiVersion: v1
kind: Service
metadata:
  name: service-service1
spec:
  selector:
    app: service1
  ports:
  - port: 80
    targetPort: 80
  type: NodePort