apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-service1
spec:
  replicas: 10
  selector:
    app: service1
  template:
    metadata:
      name: service1
      labels:
        app: service1
    spec:
      containers:
        - name: pod-service1
          image: kinhnv1801/kubeexample:service1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-service1
spec:
  selector:
    app: service1
  ports:
  - port: 80
    targetPort: 80
  type: NodePort