apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: web
        image: kinhnv1801/kube_service1:v2
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Docker"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: db
        image: mcr.microsoft.com/mssql/server
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: VanKinh1996
        ports:
          - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: service-service1
spec:
  selector:
    app: service1
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
  type: LoadBalancer